9.10 Код ревью - 2
ahwheadf/TasksJS pull request #2
Opened 2024-04-30 21:15 UTC by ahwheadf

2024-05-10 10:51 UTC, GitEsense requested changes
На доработку с комментариями

2024-05-10 10:51 UTC, GitEsense commented on 7-converter/7.10.js
> +}
Давайте сделаем несколько "позитивнее" и более читабельно через верный вариант switch case (с вложениями), тернарный оператор удобен, если мы используем "однозначный" if, но вот так и на восприятие сложно, и на чтение.
Что-то вроде такого
```js
function converter(amount, sourceCurrency, targetСurrency) {
    switch (sourceCurrency) {
        case '₽':
            switch (targetСurrency) {
                case '$': //...
                case '€': //...
                case '¥': //...
                default: //...
            }
        case '$': switch (targetСurrency) {
            case '₽': //...
            case '€': //...
            case '¥': //...
            default: //...
        }
        //...
        default: return null
    }
}
```

2024-05-10 10:51 UTC, GitEsense commented on 8-crypto/8.12.js
> +}
Давайте определим сразу два момента в функции проверки:
1. Функция принимает два значения и проверяет "не пустые ли", если да, возвращает сразу false
2. Функция никак не работает со значениями, только проверяет "пароль" и "криптопароль" через ту же функцию, что и "шифровала", иными словами
```js
function check(cryptoPassword, basicPassword){
   if(/* Тут какая-то логика */) {
      return false
   }
   return basicPassword === crypto(cryptoPassword)
}
```

2024-05-10 10:51 UTC, GitEsense commented on 8-crypto/8.12.js
> +}
Функция должна быть обратимой, т.е. если мы делаем шифрование, например
```js
const encrypt = crypto('password'); // 'ssapdorw'
const decrypt = crypto(encrypt); // 'password'
```
Тогда функция check (смотрите комментарий ниже) - будет работать "как часы" с обратимостью.
Так же рекомендую Вам найти "середину" массива, делить массив пополам и работать с обеими частями, при нечётной длине- это так же учесть, чтобы манипуляция всегда была одинакова

2024-05-10 10:51 UTC, GitEsense commented on 9-sort-loops/9.9.js
> +console.log(arrDecreasing(arr));
тут всё отлично, но можно было не делать две одинаковые функции, достаточно было добавить условие "isDescending"
Вот Ваша реализация с учётом "направления"
```js
function arrIncreasing(arr, desc = false) {
    for (let i = 0; i < arr.length; i++) {
        for (let j = 0; j < i; j++) {
            if (desc ? arr[i] < arr[j] : arr[i] > arr[j]) {
                [arr[i], arr[j]] = [arr[j], arr[i]];
            }
        }
    }
    return arr;
}
```
грубая реализация, но задачу выполняет, однако, у Вас функция модифицирует исходный массив, мы передаём массив "arr" и работаем с ним, а не нужно.
при выводе в консоль в порядке
1. arr
2. sort(arr)
3. arr

arr всегда одинаковый (изначальный), а вот sort(arr) будет результатом сортировки

2024-05-10 20:39 UTC, ahwheadf commented on 7-converter/7.10.js
> +}
Я думал над таким вариантом, но решил для себя что код с одним return на каждый case является достаточно удобно оформлен.

2024-05-14 22:51 UTC, ahwheadf commented on 9-sort-loops/9.9.js
> +console.log(arrDecreasing(arr));
"arr всегда одинаковый (изначальный), а вот sort(arr) будет результатом сортировки" - Я так и не понял как это можно реализовать без использования дополнительного массива, потому что в самой функции мы возвращаем один единственный массив, который и модифицируется.

2024-05-15 07:44 UTC, GitEsense approved these changes
В целом всё отлично, но модификацию массива всё-таки хорошо бы убрать

2024-05-15 07:44 UTC, GitEsense commented on 9-sort-loops/9.9.js
> +console.log(arrDecreasing(arr));
> "arr всегда одинаковый (изначальный), а вот sort(arr) будет результатом сортировки" - Я так и не понял как это можно реализовать без использования дополнительного массива, потому что в самой функции мы возвращаем один единственный массив, который и модифицируется.

Ну мы можем использовать новый массив , а можем на основе входящего массива создать копию по средствам slice или реструктуризации , можно и через Array.from , сам смысл в том, что параметром функции будет не конкретная переменная массива, а ссылка на него и меняя что-то там - мы по ссылке меняем его в целом

2024-05-15 07:44 UTC, GitEsense commented on 7-converter/7.10.js
> +}
Вот теперь отлично, могу предложить для ознакомления и вот такие варианты, в рамках ознакомления может быть полезно

**Простой SWITCH CASE:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}

const convertResult = converter(1500, 'rub', 'usd');
console.log(convertResult);
```

**SWITCH CASE с проверками и шаблоном:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    value = convertSum(sum, EUR, RUB); break;
                case 'USD':
                    value = convertSum(sum, EUR, USD); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
    }

    return messageTemplate(value, icon)
}

const convertResult = converter(1500, 'rub', 'usd');
console.log(convertResult);
```

**Исключительно через массив:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

Ну и запросы для "вывода"
```js
console.log(converter(100, 'RUB', 'USD')); // 1.09 $
console.log(converter(100, 'RUB', 'EUR')); // 0.89 €
console.log(converter(1000, 'EUR', 'USD')); // 1229.94 $
console.log(converter(1000, 'USD', 'EUR')); // 813.05 €
console.log(converter(1000, 'EUR', 'RUB')); // 112330.00 руб

console.log(converter(1500, 'EUR', 'RUB'));
console.log(converter(1500, 'USD', 'RUB'));

console.log(converter(10, 'RUB', 'EUR'));
console.log(converter(10, 'USD', 'EUR'));

console.log(converter(10, 'RUB', 'EURU'));
console.log(converter(10, 'USD', 'EUR'));

console.log(converter(10, 'RUB', 'EUR'));
console.log(converter(10, 'USDTY', 'EUR'));
```

2024-05-15 07:44 UTC, GitEsense commented on 9-sort-loops/9.9.js
> +}
Ну вот тут по прежнему идёт модификация массива. В занятиях шла речь о том, как нам скопировать массив (а не ссылку), чтобы не модифицировать исходный), посмотрите в сторону slice и деструктуризации, Array.from

2024-05-15 12:10 UTC, merged